### ISSUE TITLE
Unused flag

### ISSUE THREAD

**Issue by UladShumeika** [DanielMartensson/Open-SAE-J1939#22]
There is no need for the ID_and_data_is_updated flag as it is always set to true and is not reset anywhere.

**Comment by DanielMartensson** [comment]
> There is no need for the ID_and_data_is_updated flag as it is always set to true and is not reset anywhere.

Hi! 
The reason why I have this flag is because I have used this flag in e.g C++ software when I want to read like "when did I got the latest update".

This a simple way to know if the data has been arrived or not.
