### ISSUE TITLE
关于协议栈代码对每层协议处理降低耦合的想法

### ISSUE THREAD

**Issue by GIT-LEE4** [DanielMartensson/Open-SAE-J1939#26]
初步阅读了SAE_J1939-21_Transport_Layer文件夹中的代码，我认为您是计划在此文件夹中实现J1939-21：数据链路层相关的功能。
但是，我发现在其中的Request文件里，我的理解是：代码处理了J1939-73的功能，比如PGN_DM1、PGN_DM2等等。这样在以后移植程序的时候，可能会导致不必要的困难。
建议每个文件夹中，仅处理本层协议所需要的数据，其余不需要的数据在本层丢弃，或者传递给其他协议层来处理。

**Comment by DanielMartensson** [comment]
?
