### ISSUE TITLE
PIC MCU example

### ISSUE THREAD

**Issue by helikl** [DanielMartensson/Open-SAE-J1939#27]
Is there any PIC24 MCU examples?
Can I use the internal callbacks for PIC24F MCU?
Thank you.

**Comment by DanielMartensson** [comment]
> Is there any PIC24 MCU examples? Can I use the internal callbacks for PIC24F MCU? Thank you.

@helikl Hi. Use the internal feedback to create your own custom hardware layer. Or construct own internal example.
