### ISSUE TITLE
Need a flag for feedback

### ISSUE THREAD

**Issue by payapars** [DanielMartensson/Open-SAE-J1939#29]
thk  for open source stack.
1-i think this stack needed RTOS for manegment send function or PNG ID and wait to flag feedback ,so this is  need  timeout for   stack . I hope you understand what I mean!

**Comment by DanielMartensson** [comment]
What do you mean ?

**Comment by payapars** [comment]
i edited my answer!

**Comment by DanielMartensson** [comment]
> i edited my answer!

Sorry, I dont understand. Use the read messages function in your RTOS thread.

**Comment by payapars** [comment]
this my exp:

`ej1939MasterReqErrCode WriteMultiBufferData(uint8_t ucSndAddr,uint32_t PNG,uint8_t *Data,uint16_t datalen,LONG lTimeOut){
	
	
    ej1939MasterReqErrCode    eErrStatus = J1939_MRE_NO_ERR;
   // uint16_t T
    if ( ucSndAddr > J1939_MASTER_TOTAL_SLAVE_NUM ||datalen>MAX_TP_DT||datalen==NULL) eErrStatus = J1939_MRE_ILL_ARG;
    else if ( xj1939MasterRunResTake( lTimeOut ) == FALSE ) eErrStatus = J1939_MRE_MASTER_BUSY;
    else
    {
			  j1939.from_other_ecu_tp_cm.PGN_of_the_packeted_message=PNG;
		   	j1939.from_other_ecu_tp_cm.control_byte=CONTROL_BYTE_TP_CM_RTS;
			  j1939.this_ecu_tp_cm.number_of_packages=datalen/7;
				/* set number of packages, where each package will transmit up to 7 bytes */
				if (datalen % 7 > 0){
					j1939.this_ecu_tp_cm.number_of_packages+=1;	/* add extra frame if data rolls over */
				}
		    j1939.from_other_ecu_tp_cm.total_message_size=datalen;
				
				
				memcpy(&j1939.data[0],Data,datalen);
				
       SAE_J1939_Send_Transport_Protocol_Connection_Management(&j1939, ucSndAddr);
				
		   eErrStatus = ej1939MasterWaitRequestFinish(lTimeOut );
    }
    return eErrStatus;

}`

and function wait:

`ej1939MasterReqErrCode ej1939MasterWaitRequestFinish(long time_out ) {
  ej1939MasterReqErrCode    eErrStatus_Req = J1939_MRE_NO_ERR;
	uint32_t eErrStatus=J1939_MRE_NO_ERR;
          	j1939_LEDRxCpltCallback(RESET);
						j1939_LEDTxCpltCallback(SET);	
 	eErrStatus=	osEventFlagsWait (J1939_evt_id,
								EV_MASTER_PROCESS_SUCESS  
							| EV_MASTER_ERROR_RESPOND_TIMEOUT
							| EV_MASTER_ERROR_RECEIVE_DATA
							| EV_MASTER_ERROR_EXECUTE_FUNCTION,
								osFlagsWaitAny, time_out);
	
    switch (eErrStatus)
    {
					case EV_MASTER_PROCESS_SUCESS:
					{
					    eErrStatus_Req=	J1939_MRE_NO_ERR;	
							break;
					}
					case EV_MASTER_ERROR_RESPOND_TIMEOUT:
					{
							eErrStatus_Req = J1939_MRE_TIMEDOUT;
							break;
					}
					case EV_MASTER_ERROR_RECEIVE_DATA:
					{
							eErrStatus_Req = J1939_MRE_REV_DATA;
							break;
					}
					case EV_MASTER_ERROR_EXECUTE_FUNCTION:
					{
							eErrStatus_Req = J1939_MRE_EXE_FUN;
							break;
					}
					default:{
					  eErrStatus_Req =	J1939_MRE_TIMEDOUT;
						break;
					}
    }
		osEventFlagsClear (J1939_evt_id,0);
	  vj1939MasterRunResRelease( );
    return eErrStatus_Req;
		

}`

and send event of of listen function massage


`/* This function should be called all the time, or be placed inside an interrupt listener */
bool Open_SAE_J1939_Listen_For_Messages(J1939* j1939) {
	uint32_t ID = 0;
	uint8_t data[8] = {0};
	bool is_new_message = CAN_Read_Message(&ID, data);
	if(is_new_message){
		/* Save latest */
		j1939->ID = ID;
		memcpy(j1939->data, data, 8);
		j1939->ID_and_data_is_updated = true;

		uint8_t id0 = ID >> 24;
		uint8_t id1 = ID >> 16;
		uint8_t DA = ID >> 8; 	/* Destination address which is this ECU. if DA = 0xFF = broadcast to all ECU. Sometimes DA can be an ID number too */
		uint8_t SA = ID; 		/* Source address of the ECU that we got the message from */

		/* Read request from other ECU */
		if (id0 == 0x18 && id1 == 0xEA && (DA == j1939->information_this_ECU.this_ECU_address || DA == 0xFF)){
			SAE_J1939_Read_Request(j1939, SA, data);
		}else if (id0 == 0x18 && id1 == 0xD9 && DA == j1939->information_this_ECU.this_ECU_address){
			SAE_J1939_Read_Request_DM14(j1939, SA, data);

		/* Read status from other ECU */
		}else if(id0 == 0x18 && id1 == 0xE8 && DA == j1939->information_this_ECU.this_ECU_address){
			SAE_J1939_Read_Acknowledgement(j1939, SA, data);
		  **vj1939MasterCBRequestScuuess();**	
		}else if (id0 == 0x18 && id1 == 0xD8 && DA == j1939->information_this_ECU.this_ECU_address){
			SAE_J1939_Read_Response_DM15(j1939, SA, data);
		}else if(id0 == 0x18 && id1 == 0xD7 && DA == j1939->information_this_ECU.this_ECU_address){
			SAE_J1939_Read_Binary_Data_Transfer_DM16(j1939, SA, data);

		/* Read Transport Protocol information from other ECU */
		}else if(id0 == 0x1C && id1 == 0xEC && DA == j1939->information_this_ECU.this_ECU_address){
			SAE_J1939_Read_Transport_Protocol_Connection_Management(j1939, SA, data);
		}else if (id0 == 0x1C && id1 == 0xEB && DA == j1939->information_this_ECU.this_ECU_address){
			SAE_J1939_Read_Transport_Protocol_Data_Transfer(j1939, SA, data);

		/* Read response request from other ECU - This are response request. They are responses from other ECU about request from this ECU */
		}else if (id0 == 0x18 && id1 == 0xEE && DA == 0xFF && SA != 0xFE){
			SAE_J1939_Read_Response_Request_Address_Claimed(j1939, SA, data);									/* This is a broadcast response request */
		}else if (id0 == 0x18 && id1 == 0xEE && DA == 0xFF && SA == 0xFE){
			SAE_J1939_Read_Address_Not_Claimed(j1939, SA, data);												/* This is error */
		}else if (id0 == 0x18 && id1 == 0xFE && DA == 0xCA){
			SAE_J1939_Read_Response_Request_DM1(j1939, SA, data, 1); 											/* Assume that errors_dm1_active = 1 */
		}else if (id0 == 0x18 && id1 == 0xFE && DA == 0xCB){
			SAE_J1939_Read_Response_Request_DM2(j1939, SA, data, 1); 											/* Assume that errors_dm2_active = 1 */
		}else if (id0 == 0x18 && id1 == 0xFE && DA == 0xDA){
			SAE_J1939_Read_Response_Request_Software_Identification(j1939, SA, data);
		}else if (id0 == 0x18 && id1 == 0xFD && DA == 0xC5){
			SAE_J1939_Read_Response_Request_ECU_Identification(j1939, SA, data);
		}else if (id0 == 0x18 && id1 == 0xFE && DA == 0xEB){
			SAE_J1939_Read_Response_Request_Component_Identification(j1939, SA, data);
		}else if (id0 == 0x0C && id1 == 0xFE && DA >= 0x10 && DA <= 0x1F){
			ISO_11783_Read_Response_Request_Auxiliary_Estimated_Flow(j1939, SA, DA & 0xF, data);				/* DA & 0xF = Valve number. Total 16 valves from 0 to 15 */
		}else if (id0 == 0x0C && id1 == 0xC6 && DA == j1939->information_this_ECU.this_ECU_address){
			ISO_11783_Read_Response_Request_General_Purpose_Valve_Estimated_Flow(j1939, SA, data);
		}else if (id0 == 0x0C && id1 == 0xFF && DA >= 0x20 && DA <= 0x2F){
			ISO_11783_Read_Response_Request_Auxiliary_Valve_Measured_Position(j1939, SA, DA & 0xF, data); 		/* DA & 0xF = Valve number. Total 16 valves from 0 to 15 */

		/* Read command from other ECU */
		}else if (id0 == 0x0C && id1 == 0xFE && DA >= 0x30 && DA <= 0x3F){
			ISO_11783_Read_Auxiliary_Valve_Command(j1939, SA, DA & 0xF, data); 									/* DA & 0xF = Valve number. Total 16 valves from 0 to 15 */
		}else if (id0 == 0x0C && id1 == 0xC4 && DA == j1939->information_this_ECU.this_ECU_address){
			ISO_11783_Read_General_Purpose_Valve_Command(j1939, SA, data);										/* General Purpose Valve Command have only one valve */
		}else if (id0 == 0x0 && id1 == 0x2 && (DA == j1939->information_this_ECU.this_ECU_address || DA == 0xFF)){
			SAE_J1939_Read_Address_Delete(j1939, data);															/* Not a SAE J1939 standard */
		}else if (id0 == 0x1D && id1 == 0xEB && DA == j1939->information_this_ECU.this_ECU_address){
			SAE_J1939_Read_Transport_Protocol_Data_Transfer(j1939, SA, data);
		}
		else{
			is_new_message = false;																				/* The message was not meant for this ECU */
		}
		/* Add more else if statement here */
	}
	return is_new_message;
}`

**Comment by DanielMartensson** [comment]
What do you want to achieve?

**Comment by payapars** [comment]
In your code to send data if it is in master mode, there is no waiting time! Is this correct?

**Comment by DanielMartensson** [comment]
> In your code to send data if it is in master mode, there is no waiting time! Is this correct?

@payapars you can add your own delay at hardware setup of this library

**Comment by DanielMartensson** [comment]
See here.

https://github.com/DanielMartensson/Open-SAE-J1939/blob/677c5839992d37b8bb032472abc9ab7fe5559723/Src/Hardware/CAN_Transmit_Receive.c#L183

If you want to add a call back, then send me a pull request

**Comment by payapars** [comment]
thanks
