### ISSUE TITLE
HAL implementation

### ISSUE THREAD

**Issue by vChavezB** [DanielMartensson/Open-SAE-J1939#4]
Hi Daniel,

first of all thanks for your software! I am planning to use it for a project in a Lecture with students.  We will be using the Arduino platform and I will try to develop the HAL for the Arduino platform.

I see that the implementation of the HAL is done through conditional compilation. If I want to add a new implementation, source code from a specific platform would be added in the corresponding `PROCESSOR_CHOICE` macro in `CAN_Transmit_Receive.c` . When you want to scale this it can get messy as you are mixing all the hardware-specific implementations in the same file. In addition, you will need to add the respective `include` directives for the API for the respective hardware platform. 

Wouldnt it be better if the HAL interface implemented polymorphism for each specific implementation? Then each implementation would reside in its own source file. The build system could then select the HAL source files depending on the target platform. 

Regards
Victor

**Comment by DanielMartensson** [comment]
> I see that the implementation of the HAL is done through conditional compilation. If I want to add a new implementation, source code from a specific platform would be added in the corresponding `PROCESSOR_CHOICE` macro in `CAN_Transmit_Receive.c` . When you want to scale this it can get messy as you are mixing all the hardware-specific implementations in the same file. In addition, you will need to add the respective `include` directives for the API for the respective hardware platform.

> Wouldnt it be better if the HAL interface implemented polymorphism for each specific implementation? Then each implementation would reside in its own source file. The build system could then select the HAL source files depending on the target platform.

I don't think polymorphism  is easy in C. But if you have an idea, please show me. 
Normally, I just juse macros to avoid my STM32 C compiler to use Arduino C++ code. That's a simple solution.

But please. Fork the project, show me and then do a pull request.
