### ISSUE TITLE
Is there a planned release/tag for this libary?

### ISSUE THREAD

**Issue by nate-plxs** [DanielMartensson/Open-SAE-J1939#43]
Right now, it doesn't look like Open-SAE-J1939 has a tag or a release created yet. Is there a roadmap for such a release? If not, what is the assumed functionality of the library. Are there any known issues or planned features?

I'm not sure if there's a comparison of functionality between this library and commercial solutions for J1939 from Simma Software, Micro Control, or Vector.

**Comment by DanielMartensson** [comment]
@nate-plxs 
Hi!

I have no plans for release tag of this library. This library can be used at any moment and the latest update/push, is the latest release. 

This library is suitable for embedded systems in ANSI (C89) C code.

**Comment by DanielMartensson** [comment]
@nate-plxs 

New update
