### ISSUE TITLE
Proprietary arbitrary B support

### ISSUE THREAD

**Issue by clover-es** [DanielMartensson/Open-SAE-J1939#50]
Hi!

Thanks a lot for this library. Would you be interested in receiving a PR to support Proprietary Arbitrary B messages? I mean, messages in the range (0x00FF00 - 0x00FFFF).

If this is the case and you have something specific in mind for this support, please let me know.

**Comment by DanielMartensson** [comment]
@clover-es 
Yes sir. Don't forget to update the documentation .pdf as well. It's used with Libre Office.
