### ISSUE TITLE
Default Initialization of 'other_ECU_address' to 0xFF and Suggested Init Function for 'j1939' Structure

### ISSUE THREAD

**Issue by Jefferson-Lopes** [DanielMartensson/Open-SAE-J1939#53]
Hello!

I have a question regarding the **other_ECU_address** variable in this library. Is this variable always initialized to 0xFF in all use cases?

If that's the case, would it be more user-friendly to have an initialization function to set up the **j1939** structure at the start?

**Comment by DanielMartensson** [comment]
@Jefferson-Lopes 

You can add one inside ECU start up and send me a PR. :)
