### ISSUE TITLE
Is There a Method to Programmatically Derive OBD-II P-Codes from SPN, FMI, or Other J1939 Parameters Post-Parsing DTC Messages?

### ISSUE THREAD

**Issue by Anmolg1102** [DanielMartensson/Open-SAE-J1939#54]
I’m currently handling J1939 DM1 and DM2 diagnostic messages and need to map DTCs to corresponding OBD-II P-codes directly, without relying on predefined DTC tables or manual lookup resources. Specifically,  **_I want to know if there's a method or conversion algorithm that can derive the correct P-code based on parsed parameters like SPN (Suspect Parameter Number), FMI (Failure Mode Identifier), or potentially other J1939 parameters._**

Has anyone developed a systematic way or heuristic to infer OBD-II P-codes using SPN, FMI, or other available data points in J1939? Any insights or examples of a conversion technique that could dynamically map these values to related P-codes would be very helpful.

 Thank you!

**Comment by DanielMartensson** [comment]
@Anmolg1102 
Not sure what you mean. But you can read the DM1 or DM2 codes from the message. But it will only give you a number, not a plain text.

If you want to implement and send me a PR, it's welcome. Use the enum .h file inside the project.
