### ISSUE TITLE
Elements of Component_Identification(PGN 0xFEEB)

### ISSUE THREAD

**Issue by ChunBoo** [DanielMartensson/Open-SAE-J1939#56]
Hi Daniel,
     Thank you for sharing this project.
     One issue found in the struct [Component_identification ](https://github.com/DanielMartensson/Open-SAE-J1939/blob/main/Src/Open_SAE_J1939/Structs.h#L173), the first element seems is Make(SPN 586), but not "product date", not sure this one induced by different version? 
     Please correct me if my understanding was wrong.

Thanks,
Bob

**Comment by DanielMartensson** [comment]
@ChunBoo 
Can you provide me some examples or info where its stand Make(SPN)?

**Comment by ChunBoo** [comment]
> @ChunBoo Can you provide me some examples or info where its stand Make(SPN)?

Hi @Daniel, please see below screenshot:
![image](https://github.com/user-attachments/assets/d2e793d1-ac44-40c6-af9a-e665614b05ed)

**Comment by ChunBoo** [comment]
And below is codes snippet from gpt
typedef struct {
    // Extended Information
    char manufacturer_name[32];
    char component_model[32];
    char serial_number[32];
    char unit_name[32];
    uint8_t certification_data[16];
} J1939_Extended_ID;

**Comment by DanielMartensson** [comment]
> > @ChunBoo Can you provide me some examples or info where its stand Make(SPN)?
> 
> Hi @DanielMartensson , please see below screenshot:
> ![image](https://github.com/user-attachments/assets/d2e793d1-ac44-40c6-af9a-e665614b05ed)
> 

@ChunBoo 
That must be product date.

A lot of companies have their own modification of the standard.

**Comment by ChunBoo** [comment]
> > > @ChunBoo Can you provide me some examples or info where its stand Make(SPN)?
> > 
> > 
> > Hi @DanielMartensson , please see below screenshot:
> > ![image](https://private-user-images.githubusercontent.com/21964607/396001395-d2e793d1-ac44-40c6-af9a-e665614b05ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzU4MTMsIm5iZiI6MTczNDMzNTUxMywicGF0aCI6Ii8yMTk2NDYwNy8zOTYwMDEzOTUtZDJlNzkzZDEtYWM0NC00MGM2LWFmOWEtZTY2NTYxNGIwNWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3NTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYTkzZGEwNzI5MzkzMWFiYmRhODIzNWFhNTg3Mjc0MWI0ZTdhOTIxZWJmOWI2ZmI4ZGU0M2E4ZWM0Nzg2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I-RtPJwhQZwu0RhizGVGF23Er-lL8j1OBCKK_5yPQaU)
> 
> @ChunBoo That must be product date.
> 
> A lot of companies have their own modification of the standard.

Thanks, Daniel. The standard of J1939 define this product date in the Component Identification, some companies modified it as manufacturer. Got it now.

**Comment by ChunBoo** [comment]
> > > @ChunBoo Can you provide me some examples or info where its stand Make(SPN)?
> > 
> > 
> > Hi @DanielMartensson , please see below screenshot:
> > ![image](https://private-user-images.githubusercontent.com/21964607/396001395-d2e793d1-ac44-40c6-af9a-e665614b05ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMzU4MTMsIm5iZiI6MTczNDMzNTUxMywicGF0aCI6Ii8yMTk2NDYwNy8zOTYwMDEzOTUtZDJlNzkzZDEtYWM0NC00MGM2LWFmOWEtZTY2NTYxNGIwNWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDA3NTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmYTkzZGEwNzI5MzkzMWFiYmRhODIzNWFhNTg3Mjc0MWI0ZTdhOTIxZWJmOWI2ZmI4ZGU0M2E4ZWM0Nzg2Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.I-RtPJwhQZwu0RhizGVGF23Er-lL8j1OBCKK_5yPQaU)
> 
> @ChunBoo That must be product date.
> 
> A lot of companies have their own modification of the standard.

Thanks, Daniel. The standard of J1939 define this product date in the Component Identification, some companies modified it as manufacturer. Got it now.
