### ISSUE TITLE
cts

### ISSUE THREAD

**Issue by TracyCurry** [DanielMartensson/Open-SAE-J1939#59]
I find a little different definition between "j1939-2006-21.pdf" and your "Open SAE J1939.pdf". In "j1939-2006-21.pdf", it says byte2 of cts is "Number of packets that can be sent", and i think it should means that receiver tells the sender that the max number of packets it can receive instead of "total packages we have received" mentioned in "Open SAE J1939.pdf"
<img width="725" alt="pic1" src="https://github.com/user-attachments/assets/7eef2315-cde3-4050-8d32-817636dcac96" />
![pic2](https://github.com/user-attachments/assets/56463de2-9625-4ab0-b2a0-8ea63753df7f)
pic1 is from "j1939-2006-21.pdf" and pic2 is from "Open SAE J1939.pdf"

**Comment by TracyCurry** [comment]
![pic3](https://github.com/user-attachments/assets/61b4d031-7be8-43c7-9dbe-53cef09df259)
and in the code, you also set byte2 of cts for the first time as 0 which is exactly the meaning of "total packages we have received". that make me very confused

**Comment by DanielMartensson** [comment]
When, when total packages transmitted is equal as the total message, then the transition is complete.
