### ISSUE TITLE
can't find the folder "hardware"

### ISSUE THREAD

**Issue by tolshao** [DanielMartensson/Open-SAE-J1939#8]
Glad to see this excellent work, is the folder hidden for some reason.
is it possible to provide the relevant files, thanks a lot.

**Comment by DanielMartensson** [comment]
Why is it hidden?

**Comment by tolshao** [comment]
> Why is it hidden?

haha, I don't know either, can you create a release for this package?

**Comment by DanielMartensson** [comment]
> > Why is it hidden?
> 
> haha, I don't know either, can you create a release for this package?

I think this hidden-stuff is made by your operative system. Upload som printscreen here.
